language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-validate-io' ]; then cd .. && eval "mv $currentfolder generator-validate-io" && cd generator-validate-io; fi
after_script:
  - npm run coveralls

